import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
<<<<<<< HEAD
import { Providers } from "@/components/Providers";
import { Navbar } from "@/components/Navbar";
=======
>>>>>>> d418d50 (configuracion de prisma y env)

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
<<<<<<< HEAD
  title: "Tienda AWOS",
  description: "Mini Tienda Extendida (API-First)",
=======
  title: "Create Next App",
  description: "Generated by create next app",
>>>>>>> d418d50 (configuracion de prisma y env)
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
<<<<<<< HEAD
      lang="es"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col bg-gray-50 text-gray-900 font-sans">
        <Providers>
          <Navbar />
          <main className="flex-grow p-4 md:p-8">
            {children}
          </main>
        </Providers>
      </body>
=======
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
>>>>>>> d418d50 (configuracion de prisma y env)
    </html>
  );
}
